server:
  port: 8080

jwt:
  secret: pR8dXJZtG6qM9wKf3uYvL2sBzT4cV1oX5nA7mN0QWgE

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      routes:
        - id: customer-service
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/customer/**
          filters:
            - PreserveHostHeader
            - StripPrefix=0
            - AddRequestHeader=X-Forwarded-Prefix, /customer

        - id: oauth-service
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/oauth2/**
          filters:
            - PreserveHostHeader
            - StripPrefix=0
            - AddRequestHeader=X-Forwarded-Prefix, /oauth2

        - id: oauth2-callback
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/login/oauth2/code/**
          filters:
            - PreserveHostHeader
            - StripPrefix=0
            - AddRequestHeader=X-Forwarded-Prefix, /login/oauth2/code

        - id: tour-service
          uri: lb://TOURSERVICE
          predicates:
            - Path=/tour/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=X-Forwarded-Prefix, /tour

        - id: tour-service-2
          uri: lb://TOURSERVICE
          predicates:
            - Path=/tours/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=X-Forwarded-Prefix, /tours

        - id: booking-service
          uri: lb://BOOKINGSERVICE
          predicates:
            - Path=/booking/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=X-Forwarded-Prefix, /booking
    
        - id: booking-service-2
          uri: lb://BOOKINGSERVICE
          predicates:
            - Path=/bookings/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=X-Forwarded-Prefix, /bookings

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG
